export class FsmEventId
{
    public static IdName =
    {
        None: -1,
        FINISH: "FINISH",
        SHOW_SELECT_SERVER: "SHOW_SELECT_SERVER",
        SHOW_NOTICE_WINDOW: "SHOW_NOTICE_WINDOW",
        SHOW_AGE_TIP_WINDOW: "SHOW_AGE_TIP_WINDOW",
        SHOW_CREATE_ROLE_WINDOW: "SHOW_CREATE_ROLE_WINDOW",
        CREATE_ROLE: "CREATE_ROLE",
        USER_LOGIN: "USER_LOGIN",
        PLAY_GAME: "PLAY_GAME",
        ENTER_LOGIN_VIEW: "ENTER_LOGIN_VIEW",
        SERVER_OPEN_VIEW: "SERVER_OPEN_VIEW",
        LOGIN_SCENE_LOADER: "LOGIN_SCENE_LOADER",
    }
}
    